# Generated by Django 4.2.30 on 2026-06-07 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='位置名称')),
                ('room_type', models.CharField(choices=[('living', '客厅'), ('bedroom', '卧室'), ('kitchen', '厨房'), ('bathroom', '卫生间'), ('balcony', '阳台'), ('study', '书房'), ('dining', '餐厅'), ('other', '其他')], default='living', max_length=20, verbose_name='房间类型')),
                ('sunlight_level', models.CharField(choices=[('full', '全日照'), ('partial', '半日照'), ('shade', '耐阴')], default='partial', max_length=20, verbose_name='光照条件')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '摆放位置',
                'verbose_name_plural': '摆放位置',
                'ordering': ['room_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlantSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品种名称')),
                ('scientific_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='学名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('base_watering_days', models.IntegerField(default=7, verbose_name='基础浇水间隔（天）')),
                ('watering_frequency', models.CharField(choices=[('frequent', '频繁（1-3天）'), ('moderate', '适中（4-7天）'), ('infrequent', '较少（8-14天）'), ('rare', '稀少（15-30天）')], default='moderate', max_length=20, verbose_name='浇水频率')),
                ('sunlight', models.CharField(choices=[('full', '全日照'), ('partial', '半日照'), ('shade', '耐阴')], default='partial', max_length=20, verbose_name='光照需求')),
                ('min_temperature', models.IntegerField(default=10, verbose_name='最低耐受温度(℃)')),
                ('max_temperature', models.IntegerField(default=35, verbose_name='最高耐受温度(℃)')),
                ('difficulty', models.IntegerField(default=3, verbose_name='养护难度(1-5)')),
                ('toxicity', models.BooleanField(default=False, verbose_name='是否有毒')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='图片URL')),
            ],
            options={
                'verbose_name': '植物品种',
                'verbose_name_plural': '植物品种',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='植物昵称')),
                ('purchase_date', models.DateField(verbose_name='购买日期')),
                ('last_watered', models.DateField(blank=True, null=True, verbose_name='上次浇水日期')),
                ('last_fertilized', models.DateField(blank=True, null=True, verbose_name='上次施肥日期')),
                ('last_repotted', models.DateField(blank=True, null=True, verbose_name='上次换盆日期')),
                ('last_pruned', models.DateField(blank=True, null=True, verbose_name='上次修剪日期')),
                ('health_status', models.CharField(choices=[('excellent', '非常健康'), ('good', '良好'), ('fair', '一般'), ('poor', '较差'), ('critical', '危急')], default='good', max_length=20, verbose_name='健康状态')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='购买成本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.location', verbose_name='摆放位置')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plantspecies', verbose_name='品种')),
            ],
            options={
                'verbose_name': '植物',
                'verbose_name_plural': '植物',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('water', '浇水'), ('fertilize', '施肥'), ('repot', '换盆'), ('prune', '修剪'), ('other', '其他')], max_length=20, verbose_name='养护类型')),
                ('date', models.DateField(verbose_name='日期')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='花费金额')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_logs', to='plants.plant', verbose_name='植物')),
            ],
            options={
                'verbose_name': '养护记录',
                'verbose_name_plural': '养护记录',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
