# Generated by Django 4.2.30 on 2026-06-08 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('scope_type', models.CharField(choices=[('single', '单株植物'), ('room', '按房间批量'), ('all', '全部植物')], default='single', max_length=20, verbose_name='计划范围')),
                ('start_date', models.DateField(verbose_name='计划开始日期')),
                ('end_date', models.DateField(verbose_name='计划结束日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '生效中'), ('completed', '已完成'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='计划状态')),
                ('custom_rules', models.JSONField(blank=True, default=dict, verbose_name='自定义规则')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='plants.location', verbose_name='目标房间')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='plants.plant', verbose_name='目标植物')),
            ],
            options={
                'verbose_name': '养护计划',
                'verbose_name_plural': '养护计划',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='base_fertilizing_days',
            field=models.IntegerField(default=30, verbose_name='基础施肥间隔（天）'),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='base_pruning_days',
            field=models.IntegerField(default=90, verbose_name='基础修剪间隔（天）'),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='base_repotting_days',
            field=models.IntegerField(default=365, verbose_name='基础换盆间隔（天）'),
        ),
        migrations.CreateModel(
            name='CarePlanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('water', '浇水'), ('fertilize', '施肥'), ('repot', '换盆'), ('prune', '修剪')], max_length=20, verbose_name='养护类型')),
                ('scheduled_date', models.DateField(verbose_name='计划日期')),
                ('original_date', models.DateField(verbose_name='原始计划日期')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('completed', '已完成'), ('skipped', '已跳过'), ('overdue', '已逾期'), ('rescheduled', '已改期')], default='pending', max_length=20, verbose_name='任务状态')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际完成日期')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='花费金额')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('deviation_days', models.IntegerField(default=0, verbose_name='执行偏差天数')),
                ('is_auto_generated', models.BooleanField(default=True, verbose_name='是否系统自动生成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='plants.careplan', verbose_name='所属计划')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_tasks', to='plants.plant', verbose_name='目标植物')),
            ],
            options={
                'verbose_name': '养护计划任务',
                'verbose_name_plural': '养护计划任务',
                'ordering': ['scheduled_date', '-created_at'],
            },
        ),
    ]
